package vain

//go:generate go get github.com/jteeuwen/go-bindata/...
//go:generate go get github.com/elazarl/go-bindata-assetfs/...
//go:generate rm -f sql/static.go
//go:generate rm -f static.go
//go:generate go-bindata -pkg sql -o sql/static.go sql/...
//go:generate go-bindata -o static/static.go -pkg=static _static/...
